# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#this installs the newest SDK for this build
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    #performMultiLevelLookup: true
    #includePreviewVersions: true # Required for preview versions

- task: UseDotNet@2
  displayName: 'Install .NET Core Runtime'
  inputs:
    packageType: 'runtime'
    version: '2.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#SonarCloud Prepare Analysis Config
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'G1HaikuWriterSonarCloudServiceConnection'
    organization: 'g1haikuwriter'
    scannerMode: 'MSBuild'
    projectKey: 'G1HaikuWriter_P2_HaikuWriterGroup'
    projectName: 'P2_HaikuWriterGroup'

#this will restore and build repo
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'HaikuWriter/*.sln'
    workingDirectory: 'HaikuWriter'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'HaikuWriter/*.sln'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'
    testRunTitle: 'Dotnet tests running'
    workingDirectory: 'HaikuWriter'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'

# SonarCloud Run Code Analysis and Quality Gate
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# To publish
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     modifyOutputPath: false
#     workingDirectory: 'HaikuWriter/*.sln'

